# Generated by Django 3.1.2 on 2020-11-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201116_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='rate',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
