# Generated by Django 3.1.2 on 2020-12-01 15:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201128_1937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='creation_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='flag',
            field=models.BinaryField(default=0, verbose_name='Correct answer?'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='rate',
            field=models.IntegerField(default=0, verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(default='', verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to='', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=256, verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rate',
            field=models.IntegerField(default=0, verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reg_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Registration date'),
        ),
        migrations.AlterField(
            model_name='ratingusers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='blog.profile', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='word',
            field=models.CharField(max_length=256, verbose_name='Tag'),
        ),
    ]
